name: bay_lingo
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: '>=3.3.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^3.0.2

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true


  assets:
    - images/
    - assets/
    - assets/bigger_a.png
    - assets/bigger_ba.png
    - assets/bigger_da.png
    - assets/bigger_ga.png
    - assets/bigger_ha.png
    - assets/bigger_ka.png
    - assets/bigger_la.png
    - assets/bigger_ma.png
    - assets/bigger_na.png
    - assets/bigger_nga.png
    - assets/bigger_pa.png
    - assets/bigger_sa.png
    - assets/bigger_ta.png
    - assets/bigger_wa.png
    - assets/bigger_ya.png




  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
     - family: SfProDisplay
       fonts:
         - asset: fonts/SfProDisplayBlack.ttf
         - asset: fonts/SfProDisplayBold.ttf

     - family: Microsoft
       fonts:
         - asset: fonts/Microsoft_Sans_Serif.ttf

     - family: MergeOne
       fonts:
         - asset: fonts/MergeOne-Regular.ttf

     - family: Inder
       fonts:
         - asset: fonts/Inder-Regular.ttf
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
